[phases.setup]
nixPkgs = [
    "php84",
    "php84Extensions.pdo",
    "php84Extensions.pdo_mysql",
    "php84Extensions.mbstring",
    "php84Extensions.xml",
    "php84Extensions.bcmath",
    "php84Extensions.gd",
    "php84Extensions.exif",
    "php84Extensions.tokenizer",
    "php84Extensions.fileinfo",
    "php84Extensions.curl",
    "php84Extensions.zip",
    "php84Extensions.ctype",
    "php84Extensions.intl",
    "php84Extensions.openssl",
    "nodejs_20",
    "nodePackages.npm",
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci",
]

[phases.build]
cmds = [
    "npm run build",
]

[start]
cmd = "bash startup.sh"
